---
- name: manage a windows Service
  hosts: all
  gather_facts: false
  tasks:
  - name: manage {{ service_name }} service
    ansible.windows.win_service:
      name: "{{ service_name }}"
      state: "{{ service_state }}"