- name: Apply standard Registry Customizations
  hosts: all
  gather_facts: true
  vars:
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
    web_port: 80
  roles:
    - rsoliman.windows_demos.win_get_available_updates
    - rsoliman.windows_demos.win_configure_demo_webserver
    - rsoliman.windows_demos.win_generate_update_report
