---
- name: Generate a dummy file on the target host
  hosts: all
  gather_facts: false
  vars:
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
    file_path: "C:\\temp\\dummy_file.txt"
    file_size_mb: 2048
  tasks:
  - name: Make sure {{ file_path | win_dirname }} directory tree exists
    ansible.windows.win_file:
      path:  "{{ file_path | win_dirname }}"
      state: directory


  - name: Generate a dummy file of specified size
    ansible.builtin.win_shell: |
      $filePath = "{{ file_path }}"
      $fileSizeMB = {{ file_size_mb }}
      $fileSizeBytes = $fileSizeMB * 1MB
      $dummyContent = "0" * $fileSizeBytes
      Set-Content -Path $filePath -Value $dummyContent -Force
    args:
      executable: powershell
      creates: "{{ file_path }}"