---
- name: Generate a dummy file on the target host
  hosts: all
  gather_facts: false
  vars:
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
    file_path: "C:\\temp\\dummy_file.txt"
    file_size_mb: 10
  tasks:
  - name: Generate a dummy file of specified size
    ansible.builtin.win_shell: |
      $filePath = "{{ file_path }}"
      $fileSizeMB = {{ file_size_mb }}
      $fileSizeBytes = $fileSizeMB * 1MB
      $dummyContent = "0" * $fileSizeBytes
      Set-Content -Path $filePath -Value $dummyContent -Force
    args:
      executable: powershell
    creates: "{{ file_path }}"