- name: Apply standard Registry Customizations
  hosts: all
  gather_facts: false
  vars:
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
  roles:
  - rsoliman.windows_demos.win_customize_registry
