---
- name: create a new directory for the Installation files
  ansible.windows.win_file: 
    path: "{{ installer_dir }}"
    state: directory

- name: Download the installer
  ansible.windows.win_get_url:
    url: "{{ installer_url }}"
    dest: "{{ installer_dir }}\\{{ installer_name }}"

- name: Install package
  ansible.windows.win_package:
    path: "{{ installer_dir }}\\{{ installer_name }}"
    arguments: /passive

- name: delete installation files directory
  ansible.windows.win_file: 
    path: "{{ installer_dir }}"
    state: absent