namespace: rsoliman
name: windows_demos
version: 1.0.0
readme: README.md
authors:
- Raed Soliman <raedrizk@gmail.com>

description: A collection of roles used to demo AWS automation using Ansible.

license:
- "MIT"

tags: ['Windows', 'demo','ansible','raedrizk','rsoliman']

dependencies:
    "ansible.windows": "*"
    "ansible.builtin": "*"
    "community.windows": "*"
    "chocolatey.chocolatey": "*"

repository: http://example.com/repository
homepage: http://example.com
issues: http://example.com/issue/tracker
