---
- name: copying the report template 
  ansible.windows.win_template:
    src: report.html.j2
    dest: "{{ web_dir }}\\report.html"

# - name: generate report
#   ansible.builtin.template:
#     src: report.html.j2
#     dest: ./report.html
#   delegate_to: localhost
#   vars:
#     ansible_connection: local
#   run_once: true
