---
# - name: generate report
#   ansible.builtin.template:
#     src: report.html.j2
#     dest: ./report.html
#   delegate_to: localhost
#   vars:
#     ansible_connection: local
#   run_once: true

- name: Sending an e-mail
  community.general.mail:
    host: "{{ smtp_host }}"
    port: "{{ smtp_port }}"
    username: "{{ smtp_username }}"
    password: "{{ smtp_password }}"
    from: "{{ from_address }}"
    to: "{{ to_address }}"
    subject: "{{ email_subject }}"
    body: "{{ lookup('template', 'report.html.j2') }}"
  delegate_to: localhost
  vars:
    from_address: ansible@foxhound.unit
    email_subject: Windows Update report {{ ansible_date_time.time }} {{ ansible_date_time.tz }} - {{ ansible_date_time.date }}
    smtp_host: "{{ smtp_host_input | default('host.smtp.com')}}"
    smtp_port: "{{ smtp_port_input | default('587')}}"
    smtp_username: "{{ smtp_username_input | default('user@admin.com')}}"
    smtp_password: "{{ smtp_password_input | default('token')}}"
    ansible_connection: local
  run_once: true